/* This is algorand's implementation of Pointproofs */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define COMMIT_LEN 49

#define POINTPROOFSG1_LEN 48

#define POINTPROOFSG2_LEN 96

#define PP_LEN 98313

#define PROOF_LEN 49

#define VP_LEN 98889

/**
 * deserialized commitment struct
 */
typedef struct pointproofs_commitment {
  void *data;
} pointproofs_commitment;

/**
 * deserialized prover parameter struct
 */
typedef struct pointproofs_pp {
  void *data;
} pointproofs_pp;

/**
 * values
 */
typedef struct pointproofs_value {
  const uint8_t *data;
  size_t len;
} pointproofs_value;

/**
 * serialized commitment struct
 */
typedef struct pointproofs_commitment_bytes {
  uint8_t data[COMMIT_LEN];
} pointproofs_commitment_bytes;

/**
 * deserialized proof struct
 */
typedef struct pointproofs_proof {
  void *data;
} pointproofs_proof;

/**
 * deserialized verifier parameter struct
 */
typedef struct pointproofs_vp {
  void *data;
} pointproofs_vp;

/**
 * non-serialized
 */
typedef struct pointproofs_params {
  pointproofs_pp prover;
  pointproofs_vp verifier;
} pointproofs_params;

/**
 * serialized prover parameter struct
 */
typedef struct pointproofs_pp_bytes {
  uint8_t data[PP_LEN];
} pointproofs_pp_bytes;

/**
 * serialized proof struct
 */
typedef struct pointproofs_proof_bytes {
  uint8_t data[PROOF_LEN];
} pointproofs_proof_bytes;

/**
 * serialized verifer parameter struct
 */
typedef struct pointproofs_vp_bytes {
  uint8_t data[VP_LEN];
} pointproofs_vp_bytes;

/**
 * Generate a commitment
 */
pointproofs_commitment pointproofs_commit(pointproofs_pp prover,
                                          const pointproofs_value *values,
                                          uintptr_t n);

/**
 * Deserializeing bytes into commitments
 */
pointproofs_commitment pointproofs_commit_deserial(pointproofs_commitment_bytes commit);

/**
 * Serializing commitments into bytes
 */
pointproofs_commitment_bytes pointproofs_commit_serial(pointproofs_commitment commit);

/**
 * update an existing commitment
 */
pointproofs_commitment pointproofs_commit_update(pointproofs_pp prover,
                                                 pointproofs_commitment com,
                                                 size_t changed_idx,
                                                 pointproofs_value val_old,
                                                 pointproofs_value val_new);

/**
 * Free commitment
 */
void pointproofs_free_commit(pointproofs_commitment commit);

/**
 * Free proof
 */
void pointproofs_free_proof(pointproofs_proof proof);

/**
 * Free prover parameter
 */
void pointproofs_free_prover_params(pointproofs_pp pp);

/**
 * Free verifier parameter
 */
void pointproofs_free_verifier_params(pointproofs_vp vp);

/**
 * Generating a pair of parameters
 */
pointproofs_params pointproofs_paramgen(const uint8_t *seedbuf,
                                        size_t seedlen,
                                        uint8_t ciphersuite,
                                        size_t n);

/**
 * Deserializing bytes into prover parameters
 */
pointproofs_pp pointproofs_pp_deserial(pointproofs_pp_bytes pprover);

/**
 * Serializing a prove parameter into bytes
 */
pointproofs_pp_bytes pointproofs_pp_serial(pointproofs_pp pprover);

/**
 * Deserializeing bytes into proofs
 */
pointproofs_proof pointproofs_proof_deserial(pointproofs_proof_bytes proof);

/**
 * Serializing proofs into bytes
 */
pointproofs_proof_bytes pointproofs_proof_serial(pointproofs_proof proof);

/**
 * update an existing proof
 */
pointproofs_proof pointproofs_proof_update(pointproofs_pp prover,
                                           pointproofs_proof proof,
                                           size_t idx,
                                           size_t changed_idx,
                                           pointproofs_value val_old,
                                           pointproofs_value val_new);

/**
 * Generate a proof
 */
pointproofs_proof pointproofs_prove(pointproofs_pp prover,
                                    const pointproofs_value *values,
                                    uintptr_t n,
                                    size_t idx);

/**
 * aggregate proofs within a same commitment
 */
pointproofs_proof pointproofs_same_commit_aggregate(pointproofs_commitment com,
                                                    const pointproofs_proof *proofs,
                                                    const size_t *set,
                                                    const pointproofs_value *values,
                                                    size_t nvalues,
                                                    size_t param_n);

/**
 * verify an aggregated proof within a same commitment
 */
bool pointproofs_same_commit_batch_verify(pointproofs_vp verifier,
                                          pointproofs_commitment com,
                                          pointproofs_proof proof,
                                          const size_t *set,
                                          const pointproofs_value *values,
                                          size_t nvalues);

/**
 * verify the proof against the value and commitment
 */
bool pointproofs_verify(pointproofs_vp verifier,
                        pointproofs_commitment com,
                        pointproofs_proof proof,
                        pointproofs_value value,
                        size_t idx);

/**
 * Deserializing bytes into verifier parameters
 */
pointproofs_vp pointproofs_vp_deserial(pointproofs_vp_bytes pverifier);

/**
 * Serializing a verifier parameter into bytes
 */
pointproofs_vp_bytes pointproofs_vp_serial(pointproofs_vp pverifier);

/**
 * aggregated proofs cross commitments
 */
pointproofs_proof pointproofs_x_commit_aggregate_full(const pointproofs_commitment *com,
                                                      const pointproofs_proof *proof,
                                                      const size_t *set,
                                                      const pointproofs_value *values,
                                                      const size_t *commit_indices,
                                                      size_t no_commits,
                                                      size_t param_n);

/**
 * aggregated proofs cross commitments
 */
pointproofs_proof pointproofs_x_commit_aggregate_partial(const pointproofs_commitment *com,
                                                         const pointproofs_proof *agg_proof,
                                                         const size_t *set,
                                                         const pointproofs_value *values,
                                                         const size_t *commit_indices,
                                                         size_t no_commits,
                                                         size_t param_n);

/**
 * verify an aggregated proof across commitments
 */
bool pointproofs_x_commit_batch_verify(pointproofs_vp verifier,
                                       const pointproofs_commitment *com,
                                       pointproofs_proof proof,
                                       const size_t *set,
                                       const pointproofs_value *values,
                                       const size_t *commit_indices,
                                       size_t no_commits);
